let topicData=[];const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(u,o){const r=await fetch(u,o);if(!r.ok)throw Error(u);return r.json()}
function icon(name){return /chauss/i.test(name)?'👟':/vêtement/i.test(name)?'👕':/tech|dyson|électron/i.test(name)?'📱':/montre|bijou/i.test(name)?'⌚':/sac|access/i.test(name)?'👜':'✦'}
function renderTopics(list=topicData){$('#topicGrid').innerHTML=list.map(t=>`<button class="topic-card" onclick="openTopic(${t.id})"><span class="icon">${icon(t.name)}</span><strong>${esc(t.name)}</strong><small>${t.count} publication${t.count>1?'s':''}</small></button>`).join('')||'<p>Aucun topic disponible.</p>'}
function gallery(m){const urls=m.image_urls||[];return urls.length?`<div class="gallery">${urls.map((u,i)=>`<img loading="lazy" src="${esc(u)}" alt="Publication ${m.id}" onclick="event.stopPropagation();showImage('${esc(u)}')">`).join('')}</div>`:'<div class="no-media">Média non synchronisé</div>'}
async function openTopic(id){const d=await api('/api/telegram/topic/'+id);$('#topics').hidden=true;$('#topicView').hidden=false;$('#topicTitle').textContent=d.topic.name;$('#publicationGrid').innerHTML=d.topic.messages.map(m=>`<article class="publication" onclick='detail(${JSON.stringify(m)})'>${gallery(m)}<div class="pub-body"><div class="pub-meta">Publication #${m.id}</div><p>${esc(m.text||'Publication sans légende')}</p></div></article>`).join('')||'<p>Ce topic ne contient aucune publication.</p>'}
function detail(m){const el=document.createElement('div');el.className='detail';el.innerHTML=`<article><button class="close">×</button>${gallery(m)}<div class="pub-meta">Publication #${m.id}</div><p>${esc(m.text||'Publication sans légende')}</p><a href="${esc(m.telegram_url)}" target="_blank">Ouvrir la publication Telegram</a></article>`;el.querySelector('.close').onclick=()=>el.remove();el.onclick=e=>{if(e.target===el)el.remove();};document.body.append(el)}
function showImage(url){const el=document.createElement('div');el.className='lightbox';el.innerHTML=`<img src="${esc(url)}" alt="">`;el.onclick=()=>el.remove();document.body.append(el)}
$('#back').onclick=()=>{$('#topicView').hidden=true;$('#topics').hidden=false};$('#search').oninput=e=>renderTopics(topicData.filter(t=>t.name.toLowerCase().includes(e.target.value.toLowerCase())));
api('/api/telegram/topics').then(d=>{topicData=d.topics||[];renderTopics()}).catch(()=>$('#topicGrid').innerHTML='<p>Catalogue indisponible.</p>');
