let products=[],cart=JSON.parse(localStorage.getItem('lcm34cart')||'[]');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(u,o){let r=await fetch(u,o);if(!r.ok)throw Error(u);return r.json()}
function save(){localStorage.setItem('lcm34cart',JSON.stringify(cart));renderCart()}
function photo(p){if(p.has_accessible_photo&&p.image_path)return `<img loading="lazy" src="/${esc(p.image_path)}" alt="">`;return `<div class="media-pending">${p.media_status==='telegram_pending'?'📷 Photo Telegram à récupérer':'📦 Média non accessible'}</div>`}
function render(list=products){document.querySelector('#productCount').textContent=`${list.length} article${list.length>1?'s':''}`;document.querySelector('#products').innerHTML=list.length?list.map(p=>`<article class="card"><div class="card-image">${photo(p)}</div><div class="card-body"><span class="tag">${esc(p.category||'Catalogue')}</span><h3>${esc(p.title)}</h3><p>${esc(p.description||'Publication Telegram')}</p><strong>${Number(p.price)>0?p.price.toFixed(2)+' €':'Prix à confirmer'}</strong><button class="add" onclick="add(${p.id})">Ajouter au panier</button></div></article>`).join(''):'<p class="empty">Aucun article ne correspond à votre recherche.</p>'}
function add(id){let x=cart.find(i=>i.product_id===id);if(x)x.qty++;else cart.push({product_id:id,qty:1});save()}
function renderCart(){document.querySelector('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);document.querySelector('#cartItems').innerHTML=cart.length?cart.map(x=>{let p=products.find(y=>y.id===x.product_id);return p?`<div class="cart-row"><span>${esc(p.title)} × ${x.qty}</span><button onclick="cart=cart.filter(i=>i.product_id!==${p.id});save()">Retirer</button></div>`:''}).join(''):'<p class="muted">Votre panier est vide.</p>'}
function renderCategories(cats){document.querySelector('#categories').innerHTML=`<button class="filter active" data-cat="">Tout</button>`+cats.map(c=>`<button class="filter" data-cat="${esc(c.name)}">${esc(c.name)} <small>${c.product_count}</small></button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(products.filter(p=>!b.dataset.cat||p.category===b.dataset.cat))})}
async function boot(){let[p,c]=await Promise.all([api('/api/products'),api('/api/categories')]);products=p.products||[];render(products);renderCategories(c.categories||[]);renderCart()}
document.querySelector('#search').oninput=e=>{let q=e.target.value.toLowerCase();render(products.filter(p=>(p.title+' '+p.category+' '+p.description).toLowerCase().includes(q)))}
async function loginClient(){let d=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({first_name:fn.value,last_name:ln.value})});alert(d.error||'Connexion réussie')}
async function order(){if(!cart.length)return alert('Votre panier est vide.');let d=await api('/api/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart})});if(d.error)return alert(d.error);cart=[];save();alert('Commande créée : '+d.tracking)}
boot().catch(e=>{console.error(e);document.querySelector('#products').innerHTML='<p class="empty">Catalogue temporairement indisponible.</p>'});
